name: CI

on:
  pull_request:

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update npm to latest
        run: npm install -g npm@latest
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
      - run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build --if-present
      - name: Lint
        run: npm run lint --if-present
